#:kivy 1.7.2

<FormLogin>:
	spacing: 50
	padding: 50
	orientation: 'vertical'
	Label:
		font_size: 30
		size_hint: .5, .1
		text: "Username:"
		halign: 'left'
		halign: 'left'
		text_size: self.size
		pos_hint: {'center_x': .5, 'center_y': .8}
	TextInput:
		id: in_username
		font_size: 30
		size_hint: .5, .1
		multiline: False
		pos_hint: {'center_x': .5, 'center_y': .7}
	Label:
		font_size: 30
		size_hint: .5, .1
		text: "Password:"
		halign: 'left'
		text_size: self.size
		pos_hint: {'center_x': .5, 'center_y': .6}
	TextInput:
		id: in_password
		size_hint: .5, .1
		font_size: 30
		multiline: False
		pos_hint: {'center_x': .5, 'center_y': .5}
	Button:
		id: btn_submit
		on_press: root.login()
		text: 'Login'
		size_hint: .5, .1
		font_size: 30
		multiline: False
		pos_hint: {'center_x': .5, 'center_y': .38}