#:kivy 1.7.2

<FormLogin>:
	FloatLayout:
		orientation: 'vertical'
		TextInput:
			text: 'test'
			font_size: 30
			padding: 10
			size_hint: .4, .1
			multiline: False
			pos_hint: {'center_x': .5, 'center_y': .6}
		TextInput:
			size_hint: .4, .1
			font_size: 30
			padding: 10
			multiline: False
			pos_hint: {'center_x': .5, 'center_y': .5}
		Button:
			text: 'submit'
			size_hint: .4, .1
			font_size: 30
			pos_hint: {'center_x': .5, 'center_y': .4}
