#:kivy 1.7.2

<FormLogin>:
	BoxLayout:
		spacing: 50
		padding: 50
		orientation: 'vertical'
		TextInput:
			text: 'test'
			font_size: 30
			size_hint: .5, .5
			multiline: False
			pos_hint: {'center_x': .5, 'center_y': .5}
		TextInput:
			size_hint: .5, .5
			height: sp(30)
			multiline: False
			pos_hint: {'center_x': .5, 'center_y': .5}
		Button:
			size_hint: .5, .5
			height: sp(30)
			multiline: False
			pos_hint: {'center_x': .5, 'center_y': .5}